name: flax_cupertino_ui
description: Cupertino UI binding scaffold for Flax.
version: 0.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.2
  flutter: '>=3.47.2'

dependencies:
  cupertino_ui: 1.0.2
  flax: 0.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flax_codegen: 0.0.0
  flax_engine_hermes: 0.0.0
  flax_test: 0.0.0
  flutter_test:
    sdk: flutter
