export declare const MAGIC = 826496579;
export declare const VERSION = 1;
export declare const OP: {
    readonly save: 1;
    readonly restore: 2;
    readonly reset: 3;
    readonly setTransform: 4;
    readonly transform: 5;
    readonly translate: 6;
    readonly rotate: 7;
    readonly scale: 8;
    readonly resetTransform: 9;
    readonly fillRect: 10;
    readonly strokeRect: 11;
    readonly clearRect: 12;
    readonly fillPath: 13;
    readonly strokePath: 14;
    readonly clipPath: 15;
    readonly fillText: 16;
    readonly strokeText: 17;
    readonly drawImage: 18;
    readonly putImageData: 19;
    readonly setFillColor: 20;
    readonly setStrokeColor: 21;
    readonly setFillLinear: 22;
    readonly setStrokeLinear: 23;
    readonly setFillRadial: 24;
    readonly setStrokeRadial: 25;
    readonly setFillConic: 26;
    readonly setStrokeConic: 27;
    readonly setGlobalAlpha: 28;
    readonly setComposite: 29;
    readonly setLineWidth: 30;
    readonly setLineCap: 31;
    readonly setLineJoin: 32;
    readonly setMiterLimit: 33;
    readonly setLineDash: 34;
    readonly setLineDashOffset: 35;
    readonly setShadow: 36;
    readonly setSmoothing: 37;
    readonly setFilter: 38;
    readonly setFont: 39;
    readonly setTextAlign: 40;
    readonly setTextBaseline: 41;
    readonly setDirection: 42;
    readonly setLetterSpacing: 43;
    readonly setWordSpacing: 44;
    readonly setFillPattern: 45;
    readonly setStrokePattern: 46;
};
export declare const PATH: {
    readonly move: 1;
    readonly line: 2;
    readonly close: 3;
    readonly rect: 4;
    readonly cubic: 5;
    readonly quad: 6;
    readonly arc: 7;
    readonly ellipse: 8;
    readonly arcTo: 9;
    readonly roundRect: 10;
    readonly svg: 11;
    readonly add: 12;
    readonly extend: 13;
};
export type PathCommand = {
    op: number;
    numbers?: number[];
    text?: string;
    children?: PathCommand[];
};
export declare class CommandBuffer {
    buffer: ArrayBuffer;
    view: DataView<ArrayBuffer>;
    used: number;
    grow(need: number): void;
    reset(): void;
    u16(value: number): void;
    u32(value: number): void;
    f64(value: number): void;
    bytes(value: Uint8Array): void;
    text(value: string): void;
    align(): void;
    record(opcode: number, write: () => void): void;
    path(commands: readonly PathCommand[]): void;
    usedBytes(): Uint8Array;
    header(generation: number, sequence: number): Uint8Array;
}
