import 'dart:convert';
import 'dart:developer' show TimelineTask;
import 'dart:ffi';
import 'dart:io';
import 'dart:ui' show FrameTiming;

import 'package:flax/runtime.dart';
import 'package:ffi/ffi.dart';
import 'package:flax_test/runtime.dart';
import 'package:flax_test/flax_test.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import '../../../packages/flax/test/ui/native_widget_proxies_test.dart'
    as widgets;
import '../../../packages/flax/test/ui/native_callbacks_test.dart' as callbacks;
import '../../../packages/flax/test/ui/async_callbacks_test.dart' as futures;
import '../../../packages/flax/test/ui/async_stream_callbacks_test.dart'
    as async_streams;
import '../../../packages/flax/test/ui/bridge_gc_test.dart' as bridge;
import '../../../packages/flax/test/ui/streams_test.dart' as streams;
import '../../../packages/flax/test/ui/session_test.dart' as sessions;
import '../../../packages/flax/test/ui/flax_view_test.dart' as views;

void main() {
  final startup = Stopwatch()..start();
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  int? firstFrameMicros;
  binding.addPostFrameCallback(
    (_) => firstFrameMicros = startup.elapsedMicroseconds,
  );
  binding.reportData = {
    'scenario': 'engine-gc',
    'completed': true,
    if (!kDebugMode)
      'notApplicable': [
        'local frame updates and parent rebuild preserve unaffected hosts: Flutter debug rebuild hook',
        'invalidations during build wait for the next frame: Flutter debug rebuild hook',
      ],
  };
  binding.allTestsPassed.future.then((passed) {
    final result = {
      ...?binding.reportData,
      'scenario': 'engine-gc',
      'completed': passed,
      'failures': binding.failureMethodsDetails
          .map((f) => f.toString())
          .toList(),
      'cases': binding.results,
      'firstFrameMicros': firstFrameMicros,
    };
    binding.reportData = result;
    if (Platform.isAndroid) {
      // Keep the prefix and data below Android's observed 1024-byte log limit.
      final data = base64Encode(utf8.encode(jsonEncode(result)));
      const chunkSize = 800;
      for (var offset = 0; offset < data.length; offset += chunkSize) {
        final end = offset + chunkSize < data.length
            ? offset + chunkSize
            : data.length;
        debugPrintSynchronously(
          'FLAX_ENGINE_RESULT_BASE64:${data.substring(offset, end)}',
        );
      }
    } else {
      stdout.writeln('FLAX_ENGINE_RESULT:${jsonEncode(result)}');
    }
    if (const bool.fromEnvironment('FLAX_ENGINE_DIRECT_LAUNCH')) {
      final marker = passed ? 'FLAX_ENGINE_PASSED' : 'FLAX_ENGINE_FAILED';
      if (Platform.isAndroid) {
        debugPrintSynchronously(marker);
      } else {
        stdout.writeln(marker);
      }
      exit(passed ? 0 : 1);
    }
  });
  setUpAll(() async {
    if (Platform.isAndroid) {
      final libc = DynamicLibrary.open('libc.so');
      final setenv = libc
          .lookupFunction<
            Int32 Function(Pointer<Utf8>, Pointer<Utf8>, Int32),
            int Function(Pointer<Utf8>, Pointer<Utf8>, int)
          >('setenv');
      final unsetenv = libc
          .lookupFunction<
            Int32 Function(Pointer<Utf8>),
            int Function(Pointer<Utf8>)
          >('unsetenv');
      final previous = Platform.environment['FLAX_VERIFY_V8_JIT'];
      using((arena) {
        final name = 'FLAX_VERIFY_V8_JIT'.toNativeUtf8(allocator: arena);
        if (setenv(name, '1'.toNativeUtf8(allocator: arena), 1) != 0) {
          throw StateError('Cannot enable the native V8 JIT probe');
        }
        try {
          // Runtime creation fails unless the native probe observes JIT code.
          FlaxEngine.createRuntime().dispose();
          binding.reportData!['v8JitVerified'] = true;
          debugPrintSynchronously(
            'FLAX_V8_JIT: machine code generated by the embedded engine',
          );
        } finally {
          final restored = previous == null
              ? unsetenv(name)
              : setenv(name, previous.toNativeUtf8(allocator: arena), 1);
          if (restored != 0) {
            throw StateError('Cannot restore the JIT probe environment');
          }
        }
      });
    }
    final fixtures = jsonDecode(
      await rootBundle.loadString('assets/engine-fixtures.json'),
    ) as Map;
    final core = (fixtures['flax'] as Map).cast<String, String>();
    flaxTestLoadFixturePackages({'flax': core});
    await flaxTestLoadModuleAssets(core);
  });
  void register(String name, dynamic Function() body) {
    testWidgets(name, (tester) async {
      await tester.pumpWidget(
        const MaterialApp(home: Scaffold(body: Text('Flax engine GC'))),
      );
      await tester.runAsync(() async => await body());
    });
  }

  flaxRuntimeContract(FlaxEngine.createRuntime, registerTest: register);
  flaxEngineGcContract(registerTest: register);
  group('native Widgets and State', widgets.main);
  group('native callbacks', callbacks.main);
  group('Future callbacks', futures.main);
  group('Future Stream callbacks', async_streams.main);
  group('bridge GC', bridge.main);
  group('Streams', streams.main);
  group('Sessions', sessions.main);
  group('FlaxView', views.main);
  if (const bool.fromEnvironment('FLAX_ENGINE_BENCHMARK')) {
    testWidgets('profile GC, frame and memory measurements', (tester) async {
      final previousPolicy = binding.framePolicy;
      binding.framePolicy =
          LiveTestWidgetsFlutterBindingFramePolicy.benchmarkLive;
      addTearDown(() => binding.framePolicy = previousPolicy);
      await tester.pumpWidget(
        const MaterialApp(home: Center(child: CircularProgressIndicator())),
      );
      await tester.runAsync(() async {
        final startup = <int>[];
        final memory = <Map<String, int>>[];
        for (final phase in ['baseline', 'joint']) {
          FlaxJsRuntime? runtime;
          final callbacks = <FlaxJsFunction>[];
          if (phase == 'joint') {
            final watch = Stopwatch()..start();
            runtime = FlaxEngine.createRuntime();
            runtime.evaluate('''
              globalThis.heap = Array.from({length: 300000}, (_, i) => ({i}));
            ''');
            for (var i = 0; i < 1000; i++) {
              runtime.registerHostFunction(
                'owner$i',
                (_, _) => FlaxJsNumber(i.toDouble()),
              );
              callbacks.add(runtime.evaluate('owner$i') as FlaxJsFunction);
            }
            startup.add(watch.elapsedMicroseconds);
          }
          try {
            final samples = <int>[];
            final frames = <FrameTiming>[];
            binding.addTimingsCallback(frames.addAll);
            addTearDown(() => binding.removeTimingsCallback(frames.addAll));
            await Future<void>.delayed(const Duration(seconds: 2));
            final trace = TimelineTask()..start('FlaxProfile-$phase');
            for (var sample = 0; sample < 150; sample++) {
              final watch = Stopwatch()..start();
              final window = <Uint8List>[];
              for (var i = 0; i < 400; i++) {
                window.add(Uint8List(256 * 1024));
                if (window.length > 100) window.removeAt(0);
              }
              samples.add(watch.elapsedMicroseconds);
              memory.add({
                'rss': ProcessInfo.currentRss,
                'maxRss': ProcessInfo.maxRss,
              });
              await Future<void>.delayed(const Duration(milliseconds: 100));
            }
            trace.finish();
            await Future<void>.delayed(const Duration(seconds: 2));
            binding.reportData!['$phase-allocationMicros'] = samples;
            binding.reportData!['$phase-frameMicros'] = [
              for (final frame in frames)
                {
                  'build': frame.buildDuration.inMicroseconds,
                  'raster': frame.rasterDuration.inMicroseconds,
                  'total': frame.totalSpan.inMicroseconds,
                },
            ];
            binding.removeTimingsCallback(frames.addAll);
            if (callbacks.isNotEmpty) {
              expect((callbacks.first.call([]) as FlaxJsNumber).value, 0);
              expect((callbacks.last.call([]) as FlaxJsNumber).value, 999);
            }
          } finally {
            for (final callback in callbacks) {
              callback.release();
            }
            runtime?.dispose();
          }
        }
        binding.reportData!['runtimeAnd300kHeapStartupMicros'] = startup;
        binding.reportData!['workload'] = {
          'ordinaryJsObjects': 300000,
          'liveCallbackPairs': 1000,
          'allocationSamples': 150,
          'allocationsPerSample': 400,
          'allocationBytes': 256 * 1024,
        };
        binding.reportData!['memorySamples'] = memory;
      });
      await tester.pumpWidget(const SizedBox.shrink());
    });
  }
}
