name: flax_material_ui
description: Material UI binding scaffold for Flax.
version: 0.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0
  flutter: '>=3.47.0'

dependencies:
  flax: 0.0.0
  flutter:
    sdk: flutter
  material_ui: 1.1.1
