// Generated from the canonical V8 adapter header. Do not edit by hand.
// ignore_for_file: type=lint

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:flax_engine_v8/flax_engine_v8.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Uint32)>()
external ffi.Pointer<ffi.Void> flax_v8_get_api(int version);
