name: flax
description: Experimental JS runtime, generated bindings, and Flutter host for Flax.
version: 0.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.2
  flutter: '>=3.47.2'

dependencies:
  ffi: 2.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flax_test: 0.0.0
  flax_codegen: 0.0.0
  flax_engine_hermes: 0.0.0
  flutter_test:
    sdk: flutter
  material_ui: 1.1.1
