// Generated from the canonical Flax C headers. Do not edit by hand.
// ignore_for_file: type=lint

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

const int FLAX_ABI_VERSION = 2;

const int FLAX_CALLBACK_FAILURE = 4;

final class FlaxApi extends ffi.Struct {
  @ffi.Uint32()
  external int version;

  @ffi.Size()
  external int struct_size;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<ffi.Pointer<FlaxRuntime>> runtime,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  create;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  destroy;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        ffi.Pointer<ffi.Uint8> source,
        ffi.Size source_length,
        ffi.Pointer<ffi.Uint8> source_url,
        ffi.Size source_url_length,
        ffi.Pointer<FlaxValueId> result,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  evaluate;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        ffi.Pointer<FlaxValueId> result,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  global_object;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        ffi.Int32 kind,
        ffi.Double number,
        ffi.Pointer<ffi.Uint16> string_data,
        ffi.Size string_length,
        ffi.Pointer<FlaxValueId> result,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  make_value;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        FlaxValueId value,
        ffi.Pointer<FlaxValueInfo> info,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  inspect;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        FlaxValueId value,
        ffi.Pointer<FlaxValueId> result,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  clone_value;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        FlaxValueId value,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  release_value;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        FlaxValueId object,
        ffi.Pointer<ffi.Uint16> name,
        ffi.Size name_length,
        ffi.Pointer<FlaxValueId> result,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  get_property;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        FlaxValueId object,
        ffi.Pointer<ffi.Uint16> name,
        ffi.Size name_length,
        FlaxValueId value,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  set_property;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        FlaxValueId function,
        FlaxValueId this_value,
        ffi.Pointer<FlaxValueId> arguments,
        ffi.Size count,
        ffi.Pointer<FlaxValueId> result,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  call;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        FlaxValueId left,
        FlaxValueId right,
        ffi.Pointer<ffi.Int32> result,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  strict_equals;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        ffi.Pointer<ffi.Uint16> name,
        ffi.Size name_length,
        FlaxHostCallback callback,
        ffi.Pointer<ffi.Void> context,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  register_host;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        ffi.Int32 hint,
        ffi.Pointer<ffi.Int32> complete,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  drain_microtasks;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        ffi.Pointer<ffi.Uint8> data,
        ffi.Size length,
        ffi.Pointer<FlaxValueId> result,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  make_bytes;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<FlaxRuntime> runtime,
        FlaxValueId value,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>> data,
        ffi.Pointer<ffi.Size> length,
        ffi.Pointer<FlaxError> error,
      )
    >
  >
  read_bytes;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> buffer)>
  >
  buffer_free;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FlaxError> error)>
  >
  error_clear;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<FlaxError> error,
        ffi.Int32 code,
        ffi.Pointer<ffi.Uint8> message,
        ffi.Size message_length,
        ffi.Pointer<ffi.Uint8> stack,
        ffi.Size stack_length,
      )
    >
  >
  error_set;

  static ffi.Pointer<FlaxApi> $allocate(
    ffi.Allocator $allocator, {
    required int version,
    required int struct_size,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<ffi.Pointer<FlaxRuntime>> runtime,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    create,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    destroy,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          ffi.Pointer<ffi.Uint8> source,
          ffi.Size source_length,
          ffi.Pointer<ffi.Uint8> source_url,
          ffi.Size source_url_length,
          ffi.Pointer<FlaxValueId> result,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    evaluate,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          ffi.Pointer<FlaxValueId> result,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    global_object,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          ffi.Int32 kind,
          ffi.Double number,
          ffi.Pointer<ffi.Uint16> string_data,
          ffi.Size string_length,
          ffi.Pointer<FlaxValueId> result,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    make_value,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          FlaxValueId value,
          ffi.Pointer<FlaxValueInfo> info,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    inspect,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          FlaxValueId value,
          ffi.Pointer<FlaxValueId> result,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    clone_value,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          FlaxValueId value,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    release_value,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          FlaxValueId object,
          ffi.Pointer<ffi.Uint16> name,
          ffi.Size name_length,
          ffi.Pointer<FlaxValueId> result,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    get_property,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          FlaxValueId object,
          ffi.Pointer<ffi.Uint16> name,
          ffi.Size name_length,
          FlaxValueId value,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    set_property,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          FlaxValueId function,
          FlaxValueId this_value,
          ffi.Pointer<FlaxValueId> arguments,
          ffi.Size count,
          ffi.Pointer<FlaxValueId> result,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    call,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          FlaxValueId left,
          FlaxValueId right,
          ffi.Pointer<ffi.Int32> result,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    strict_equals,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          ffi.Pointer<ffi.Uint16> name,
          ffi.Size name_length,
          FlaxHostCallback callback,
          ffi.Pointer<ffi.Void> context,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    register_host,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          ffi.Int32 hint,
          ffi.Pointer<ffi.Int32> complete,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    drain_microtasks,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          ffi.Pointer<ffi.Uint8> data,
          ffi.Size length,
          ffi.Pointer<FlaxValueId> result,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    make_bytes,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<FlaxRuntime> runtime,
          FlaxValueId value,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>> data,
          ffi.Pointer<ffi.Size> length,
          ffi.Pointer<FlaxError> error,
        )
      >
    >
    read_bytes,
    required ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> buffer)>
    >
    buffer_free,
    required ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FlaxError> error)>
    >
    error_clear,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<FlaxError> error,
          ffi.Int32 code,
          ffi.Pointer<ffi.Uint8> message,
          ffi.Size message_length,
          ffi.Pointer<ffi.Uint8> stack,
          ffi.Size stack_length,
        )
      >
    >
    error_set,
  }) => $allocator<FlaxApi>()
    ..ref.version = version
    ..ref.struct_size = struct_size
    ..ref.create = create
    ..ref.destroy = destroy
    ..ref.evaluate = evaluate
    ..ref.global_object = global_object
    ..ref.make_value = make_value
    ..ref.inspect = inspect
    ..ref.clone_value = clone_value
    ..ref.release_value = release_value
    ..ref.get_property = get_property
    ..ref.set_property = set_property
    ..ref.call = call
    ..ref.strict_equals = strict_equals
    ..ref.register_host = register_host
    ..ref.drain_microtasks = drain_microtasks
    ..ref.make_bytes = make_bytes
    ..ref.read_bytes = read_bytes
    ..ref.buffer_free = buffer_free
    ..ref.error_clear = error_clear
    ..ref.error_set = error_set;
}

final class FlaxError extends ffi.Struct {
  @ffi.Int32()
  external int code;

  external ffi.Pointer<ffi.Uint8> message;

  @ffi.Size()
  external int message_length;

  external ffi.Pointer<ffi.Uint8> stack;

  @ffi.Size()
  external int stack_length;

  static ffi.Pointer<FlaxError> $allocate(
    ffi.Allocator $allocator, {
    required int code,
    required ffi.Pointer<ffi.Uint8> message,
    required int message_length,
    required ffi.Pointer<ffi.Uint8> stack,
    required int stack_length,
  }) => $allocator<FlaxError>()
    ..ref.code = code
    ..ref.message = message
    ..ref.message_length = message_length
    ..ref.stack = stack
    ..ref.stack_length = stack_length;
}

typedef FlaxHostCallback =
    ffi.Pointer<ffi.NativeFunction<FlaxHostCallbackFunction>>;
typedef FlaxHostCallbackFunction = ffi.Int32 Function(
  ffi.Pointer<ffi.Void> context,
  ffi.Pointer<FlaxRuntime> runtime,
  FlaxValueId this_value,
  ffi.Pointer<FlaxValueId> arguments,
  ffi.Size count,
  ffi.Pointer<FlaxValueId> result,
  ffi.Pointer<FlaxError> error,
);
typedef DartFlaxHostCallbackFunction = int Function(
  ffi.Pointer<ffi.Void> context,
  ffi.Pointer<FlaxRuntime> runtime,
  DartFlaxValueId this_value,
  ffi.Pointer<FlaxValueId> arguments,
  int count,
  ffi.Pointer<FlaxValueId> result,
  ffi.Pointer<FlaxError> error,
);

final class FlaxRuntime extends ffi.Opaque {}

enum FlaxStatus {
  FLAX_OK(0),
  FLAX_JS_ERROR(1),
  FLAX_STATE_ERROR(2),
  FLAX_ARGUMENT_ERROR(3),
  FLAX_NATIVE_ERROR(4);

  final int value;
  const FlaxStatus(this.value);

  static FlaxStatus fromValue(int value) => switch (value) {
    0 => FLAX_OK,
    1 => FLAX_JS_ERROR,
    2 => FLAX_STATE_ERROR,
    3 => FLAX_ARGUMENT_ERROR,
    4 => FLAX_NATIVE_ERROR,
    _ => throw ArgumentError('Unknown value for FlaxStatus: $value'),
  };
}

typedef FlaxValueId = ffi.Uint64;
typedef DartFlaxValueId = int;

final class FlaxValueInfo extends ffi.Struct {
  @ffi.Int32()
  external int kind;

  @ffi.Double()
  external double number;

  external ffi.Pointer<ffi.Uint16> string_data;

  @ffi.Size()
  external int string_length;

  static ffi.Pointer<FlaxValueInfo> $allocate(
    ffi.Allocator $allocator, {
    required int kind,
    required double number,
    required ffi.Pointer<ffi.Uint16> string_data,
    required int string_length,
  }) => $allocator<FlaxValueInfo>()
    ..ref.kind = kind
    ..ref.number = number
    ..ref.string_data = string_data
    ..ref.string_length = string_length;
}

enum FlaxValueKind {
  FLAX_UNDEFINED(0),
  FLAX_NULL(1),
  FLAX_BOOLEAN(2),
  FLAX_NUMBER(3),
  FLAX_STRING(4),
  FLAX_OBJECT(5),
  FLAX_FUNCTION(6);

  final int value;
  const FlaxValueKind(this.value);

  static FlaxValueKind fromValue(int value) => switch (value) {
    0 => FLAX_UNDEFINED,
    1 => FLAX_NULL,
    2 => FLAX_BOOLEAN,
    3 => FLAX_NUMBER,
    4 => FLAX_STRING,
    5 => FLAX_OBJECT,
    6 => FLAX_FUNCTION,
    _ => throw ArgumentError('Unknown value for FlaxValueKind: $value'),
  };
}
